GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6315bd01a97c7e5760b440b4

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person 11",
    "subscribedToChannel": "Web Dev Simplified 11"
}

###

POST  http://localhost:3000/subscribers/createStudent
Content-Type: application/json

{
    "name": "Jitendra Tiwari2",
    "email": "jit@gmail2"
}

###

DELETE http://localhost:3000/subscribers/6315bd01a97c7e5760b440b4

###

PATCH  http://localhost:3000/subscribers/6315a735bf5e8c40c4402fb9
Content-Type: application/json

{
    "name":"New Name22"
}